# Generated by Django 2.2.12 on 2021-11-27 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='receipt_no',
            field=models.TextField(),
        ),
    ]
